/* generated using openapi-typescript-codegen -- do not edit */
/* istanbul ignore file */
/* tslint:disable */
/* eslint-disable */
export { ApiError } from './core/ApiError';
export { CancelablePromise, CancelError } from './core/CancelablePromise';
export { OpenAPI } from './core/OpenAPI';
export type { OpenAPIConfig } from './core/OpenAPI';

export { AccessType } from './models/AccessType';
export type { AddCompositionToPubDealRequest } from './models/AddCompositionToPubDealRequest';
export type { AddMasterToDealRequest } from './models/AddMasterToDealRequest';
export type { AddReleaseAssetRequest } from './models/AddReleaseAssetRequest';
export type { Address } from './models/Address';
export type { AddSongwriterRequest } from './models/AddSongwriterRequest';
export type { AddTeamMemberRequest } from './models/AddTeamMemberRequest';
export { AgreementStatus } from './models/AgreementStatus';
export type { ArtistDetailResponse } from './models/ArtistDetailResponse';
export type { ArtistDetailsRequest } from './models/ArtistDetailsRequest';
export type { ArtistMemberResponse } from './models/ArtistMemberResponse';
export type { ArtistResponseSkinny } from './models/ArtistResponseSkinny';
export type { ArtistSearchResult } from './models/ArtistSearchResult';
export type { ArtistSummaryResponse } from './models/ArtistSummaryResponse';
export { AssetCatalogTier } from './models/AssetCatalogTier';
export type { BankingInfoResponse } from './models/BankingInfoResponse';
export type { BankingInformation } from './models/BankingInformation';
export type { Body_add_file_asset_api_v1_releases__release_number__assets__media_type___asset_type__post } from './models/Body_add_file_asset_api_v1_releases__release_number__assets__media_type___asset_type__post';
export type { Body_add_track_file_asset_api_v1_releases__release_number__track__track_number__asset__asset_type__post } from './models/Body_add_track_file_asset_api_v1_releases__release_number__track__track_number__asset__asset_type__post';
export type { Body_extract_deal_data_api_v1_deals_extract_deal_data_post } from './models/Body_extract_deal_data_api_v1_deals_extract_deal_data_post';
export type { Body_upload_agreement_api_v1_livePerformanceDeals__deal_number__agreement_post } from './models/Body_upload_agreement_api_v1_livePerformanceDeals__deal_number__agreement_post';
export type { Body_upload_agreement_api_v1_masterDeals__deal_number__agreement_post } from './models/Body_upload_agreement_api_v1_masterDeals__deal_number__agreement_post';
export type { Body_upload_agreement_api_v1_neighboringRightsDeals__deal_number__agreement_post } from './models/Body_upload_agreement_api_v1_neighboringRightsDeals__deal_number__agreement_post';
export type { Body_upload_agreement_api_v1_publishingDeals__deal_number__agreement_post } from './models/Body_upload_agreement_api_v1_publishingDeals__deal_number__agreement_post';
export type { Body_upload_agreement_api_v1_recordDeals__deal_number__agreement_post } from './models/Body_upload_agreement_api_v1_recordDeals__deal_number__agreement_post';
export type { Body_upload_agreement_api_v1_simpleRoyaltyDeals__deal_number__agreement_post } from './models/Body_upload_agreement_api_v1_simpleRoyaltyDeals__deal_number__agreement_post';
export type { Body_upload_agreement_api_v1_syncLicenseDeals__deal_number__agreement_post } from './models/Body_upload_agreement_api_v1_syncLicenseDeals__deal_number__agreement_post';
export type { Body_upload_pro_csv_api_v1_clients__book_number__proExtract__pro__post } from './models/Body_upload_pro_csv_api_v1_clients__book_number__proExtract__pro__post';
export type { Body_upload_profile_image_api_v1_artists__artist_number__profile_image_post } from './models/Body_upload_profile_image_api_v1_artists__artist_number__profile_image_post';
export type { Body_upload_profile_image_api_v1_people__person_number__profile_image_post } from './models/Body_upload_profile_image_api_v1_people__person_number__profile_image_post';
export type { Body_upload_w9_api_v1_clients__book_number__w9_post } from './models/Body_upload_w9_api_v1_clients__book_number__w9_post';
export type { BookPublishingDealInfo } from './models/BookPublishingDealInfo';
export { BookType } from './models/BookType';
export type { BulkDeleteMastersRequest } from './models/BulkDeleteMastersRequest';
export type { BulkDeleteSongsRequest } from './models/BulkDeleteSongsRequest';
export type { BusinessCardConfigResponse } from './models/BusinessCardConfigResponse';
export type { BusinessCardResponse } from './models/BusinessCardResponse';
export type { CachedExtractionData } from './models/CachedExtractionData';
export type { CardArtistProjects } from './models/CardArtistProjects';
export type { CardSongwriterDetails } from './models/CardSongwriterDetails';
export type { CatalogOverview } from './models/CatalogOverview';
export type { Clearance } from './models/Clearance';
export type { ClientDetailResponse } from './models/ClientDetailResponse';
export type { ClientSummaryResponse } from './models/ClientSummaryResponse';
export type { Collaborator } from './models/Collaborator';
export type { CollaboratorOutput } from './models/CollaboratorOutput';
export { CollectionMandate } from './models/CollectionMandate';
export type { CompositionAgreementResponse } from './models/CompositionAgreementResponse';
export { CompositionAgreementVisibilityStatus } from './models/CompositionAgreementVisibilityStatus';
export { CompositionRole } from './models/CompositionRole';
export type { ConfirmMasterUploadRequest } from './models/ConfirmMasterUploadRequest';
export type { ContactInfo } from './models/ContactInfo';
export type { ContractingInfoResponse } from './models/ContractingInfoResponse';
export type { ContributorResponse } from './models/ContributorResponse';
export { ContributorRole } from './models/ContributorRole';
export type { CreateArtistMembershipRequest } from './models/CreateArtistMembershipRequest';
export type { CreateArtistRequest } from './models/CreateArtistRequest';
export type { CreateClientBankingInfoRequest } from './models/CreateClientBankingInfoRequest';
export type { CreateClientRequest } from './models/CreateClientRequest';
export type { CreateCompositionAgreementRequest } from './models/CreateCompositionAgreementRequest';
export type { CreateContractingInfoRequest } from './models/CreateContractingInfoRequest';
export type { CreateContributorRequest } from './models/CreateContributorRequest';
export type { CreateInvoiceClientRequest } from './models/CreateInvoiceClientRequest';
export type { CreateInvoiceRequest } from './models/CreateInvoiceRequest';
export type { CreateISRCRequest } from './models/CreateISRCRequest';
export type { CreateLivePerformanceDealRequest } from './models/CreateLivePerformanceDealRequest';
export type { CreateManagerRequest } from './models/CreateManagerRequest';
export type { CreateMasterAgreementRequest } from './models/CreateMasterAgreementRequest';
export type { CreateMasterArtistRequest } from './models/CreateMasterArtistRequest';
export type { CreateMasterBonusRequest } from './models/CreateMasterBonusRequest';
export type { CreateMasterCreditRequest } from './models/CreateMasterCreditRequest';
export type { CreateMasterDealRequest } from './models/CreateMasterDealRequest';
export type { CreateMasterRequest } from './models/CreateMasterRequest';
export type { CreateNeighboringRightsDealRequest } from './models/CreateNeighboringRightsDealRequest';
export type { CreatePubDealContactRequest } from './models/CreatePubDealContactRequest';
export type { CreatePubDealRequest } from './models/CreatePubDealRequest';
export type { CreatePublisherEntityRequest } from './models/CreatePublisherEntityRequest';
export type { CreateRecordDealRequest } from './models/CreateRecordDealRequest';
export type { CreateReleaseEventRequest } from './models/CreateReleaseEventRequest';
export type { CreateReleasePermissionsRequest } from './models/CreateReleasePermissionsRequest';
export type { CreateReleaseRequest } from './models/CreateReleaseRequest';
export type { CreateShowRequest } from './models/CreateShowRequest';
export type { CreateSimpleRoyaltyDealRequest } from './models/CreateSimpleRoyaltyDealRequest';
export type { CreateSongRequest } from './models/CreateSongRequest';
export type { CreateSongwriterIdentityRequest } from './models/CreateSongwriterIdentityRequest';
export type { CreateSyncLicenseDealRequest } from './models/CreateSyncLicenseDealRequest';
export type { CreateTeamRequest } from './models/CreateTeamRequest';
export type { CreateTrackRequest } from './models/CreateTrackRequest';
export type { CreateUserIntegrationRequest } from './models/CreateUserIntegrationRequest';
export { Currency } from './models/Currency';
export type { DealIngestionMetadata } from './models/DealIngestionMetadata';
export type { DealInvoiceSummaryResponse } from './models/DealInvoiceSummaryResponse';
export type { DealParty } from './models/DealParty';
export { DealPartyType } from './models/DealPartyType';
export type { DealsOverview } from './models/DealsOverview';
export { DealStatus } from './models/DealStatus';
export type { DealSummaryResponse } from './models/DealSummaryResponse';
export { DealType } from './models/DealType';
export type { DealUser } from './models/DealUser';
export type { DeliverReleaseDDEXRequest } from './models/DeliverReleaseDDEXRequest';
export { DeliveryJobStatus } from './models/DeliveryJobStatus';
export type { DeliveryJobStatusFullResponse } from './models/DeliveryJobStatusFullResponse';
export type { EnrichBookRequest } from './models/EnrichBookRequest';
export { EnrichmentType } from './models/EnrichmentType';
export type { EventModel } from './models/EventModel';
export type { ExtractDealDataJobCreationResponse } from './models/ExtractDealDataJobCreationResponse';
export { ExtractDealDataStatus } from './models/ExtractDealDataStatus';
export { FeaturedSocialLinkChoices } from './models/FeaturedSocialLinkChoices';
export { FeeSchedule } from './models/FeeSchedule';
export type { FirebaseUserStub } from './models/FirebaseUserStub';
export type { GetSongsCSVRequest } from './models/GetSongsCSVRequest';
export type { HTTPValidationError } from './models/HTTPValidationError';
export type { IncompleteSongsResponse } from './models/IncompleteSongsResponse';
export type { IngestDealDataRequest } from './models/IngestDealDataRequest';
export type { IngestionArtistStatus } from './models/IngestionArtistStatus';
export type { IngestionMasterAgreementStatus } from './models/IngestionMasterAgreementStatus';
export type { IngestionMasterStatus } from './models/IngestionMasterStatus';
export type { IngestionOrganizationStatus } from './models/IngestionOrganizationStatus';
export type { IngestionPersonStatus } from './models/IngestionPersonStatus';
export { IntegrationDeliveryStatus } from './models/IntegrationDeliveryStatus';
export type { IntegrationDeliveryStatusResponse } from './models/IntegrationDeliveryStatusResponse';
export type { IntegrationResponse } from './models/IntegrationResponse';
export { IntegrationType } from './models/IntegrationType';
export type { InviteSummaryResponse } from './models/InviteSummaryResponse';
export type { InvoiceClientResponse } from './models/InvoiceClientResponse';
export { InvoiceFilenameConfigField } from './models/InvoiceFilenameConfigField';
export type { InvoiceFilenameConfigResponse } from './models/InvoiceFilenameConfigResponse';
export type { InvoiceLineItem } from './models/InvoiceLineItem';
export type { InvoiceResponse } from './models/InvoiceResponse';
export type { InvoicesOverview } from './models/InvoicesOverview';
export { InvoiceStatus } from './models/InvoiceStatus';
export { IPINameType } from './models/IPINameType';
export type { ISRCInfoResponse } from './models/ISRCInfoResponse';
export type { LabelRegistrantResponse } from './models/LabelRegistrantResponse';
export type { LivePerformanceDealResponse } from './models/LivePerformanceDealResponse';
export { LivePerformanceDealType } from './models/LivePerformanceDealType';
export type { ManagerResponse } from './models/ManagerResponse';
export { ManagerRole } from './models/ManagerRole';
export type { ManagerSummaryResponse } from './models/ManagerSummaryResponse';
export type { MasterAgreementResponse } from './models/MasterAgreementResponse';
export { MasterAgreementType } from './models/MasterAgreementType';
export type { MasterArtistRequest } from './models/MasterArtistRequest';
export { MasterArtistRole } from './models/MasterArtistRole';
export type { MasterArtistSummary } from './models/MasterArtistSummary';
export type { MasterBonusResponse } from './models/MasterBonusResponse';
export { MasterCreditType } from './models/MasterCreditType';
export type { MasterDealDetailResponse } from './models/MasterDealDetailResponse';
export { MasterDealResponseSkinny } from './models/MasterDealResponseSkinny';
export { MasterDealType } from './models/MasterDealType';
export type { MasterDetailResponse } from './models/MasterDetailResponse';
export { MasterPerformanceRole } from './models/MasterPerformanceRole';
export { MasterRoyaltyType } from './models/MasterRoyaltyType';
export { MasterStatus } from './models/MasterStatus';
export { MasterSubmissionState } from './models/MasterSubmissionState';
export type { MasterSummaryResponse } from './models/MasterSummaryResponse';
export type { MasterTechnicalDetailsRequest } from './models/MasterTechnicalDetailsRequest';
export type { MasterTechnicalDetailsResponse } from './models/MasterTechnicalDetailsResponse';
export type { MasterTrackResponse } from './models/MasterTrackResponse';
export { MasterType } from './models/MasterType';
export type { NamedNumberedObject } from './models/NamedNumberedObject';
export type { NeighboringRightsDealResponse } from './models/NeighboringRightsDealResponse';
export type { OrganizationRequest } from './models/OrganizationRequest';
export type { OrganizationResponse } from './models/OrganizationResponse';
export type { OrganizationSummaryResponse } from './models/OrganizationSummaryResponse';
export { OrganizationType } from './models/OrganizationType';
export type { OverviewResponse } from './models/OverviewResponse';
export { ParentalAdvisory } from './models/ParentalAdvisory';
export { ParentalWarning } from './models/ParentalWarning';
export { PaymentStatus } from './models/PaymentStatus';
export { PermissionAxis } from './models/PermissionAxis';
export type { PersonDetailResponse } from './models/PersonDetailResponse';
export type { PersonDetails } from './models/PersonDetails';
export { PersonRoleDescriptor } from './models/PersonRoleDescriptor';
export type { PersonSummaryResponse } from './models/PersonSummaryResponse';
export type { PersonUpdateRequest } from './models/PersonUpdateRequest';
export { PreorderType } from './models/PreorderType';
export type { PROAttachmentRequest } from './models/PROAttachmentRequest';
export { PROCsvType } from './models/PROCsvType';
export type { PROExtractHistoryResponse } from './models/PROExtractHistoryResponse';
export { ProfessionalRole } from './models/ProfessionalRole';
export type { PROSummaryResponse } from './models/PROSummaryResponse';
export type { PubDealContactResponse } from './models/PubDealContactResponse';
export type { PubDealEntityRequest } from './models/PubDealEntityRequest';
export type { PubDealEntityResponse } from './models/PubDealEntityResponse';
export type { PubDealResponse } from './models/PubDealResponse';
export type { PubDealResponseSkinny } from './models/PubDealResponseSkinny';
export type { PublisherEntityResponse } from './models/PublisherEntityResponse';
export { PublishingDealType } from './models/PublishingDealType';
export type { RecordDealResponse } from './models/RecordDealResponse';
export type { RecordDealResponseSkinny } from './models/RecordDealResponseSkinny';
export { RecordDealType } from './models/RecordDealType';
export type { RedeemReferralRequest } from './models/RedeemReferralRequest';
export { RegistrationStatus } from './models/RegistrationStatus';
export { ReleaseAccessType } from './models/ReleaseAccessType';
export type { ReleaseArtistRequest } from './models/ReleaseArtistRequest';
export type { ReleaseArtistResponse } from './models/ReleaseArtistResponse';
export type { ReleaseArtistSummary } from './models/ReleaseArtistSummary';
export { ReleaseArtistType } from './models/ReleaseArtistType';
export { ReleaseAssetMediaType } from './models/ReleaseAssetMediaType';
export type { ReleaseAssetPlaybackUrlResponse } from './models/ReleaseAssetPlaybackUrlResponse';
export type { ReleaseAssetResponse } from './models/ReleaseAssetResponse';
export { ReleaseAssetType } from './models/ReleaseAssetType';
export type { ReleaseAssetUploadLinkResponse } from './models/ReleaseAssetUploadLinkResponse';
export type { ReleaseDetailResponse } from './models/ReleaseDetailResponse';
export type { ReleaseMasterUploadConfirmResponse } from './models/ReleaseMasterUploadConfirmResponse';
export type { ReleaseMasterUploadLinkResponse } from './models/ReleaseMasterUploadLinkResponse';
export type { ReleasePermissionsResponse } from './models/ReleasePermissionsResponse';
export { ReleaseProduct } from './models/ReleaseProduct';
export type { ReleaseResponseSkinny } from './models/ReleaseResponseSkinny';
export type { ReleasesOverview } from './models/ReleasesOverview';
export { ReleaseStatus } from './models/ReleaseStatus';
export type { ReleaseSummaryResponse } from './models/ReleaseSummaryResponse';
export { ReleaseTerritory } from './models/ReleaseTerritory';
export type { ReleaseTerritoryDetailResponse } from './models/ReleaseTerritoryDetailResponse';
export type { ReleaseTerritoryRequest } from './models/ReleaseTerritoryRequest';
export type { ReleaseTerritoryResponse } from './models/ReleaseTerritoryResponse';
export { ReleaseTiming } from './models/ReleaseTiming';
export type { ReleaseValidationResponse } from './models/ReleaseValidationResponse';
export type { ReleaseValidationSection } from './models/ReleaseValidationSection';
export { ReportType } from './models/ReportType';
export { ReversionType } from './models/ReversionType';
export type { SelfResponse } from './models/SelfResponse';
export type { SendSongSplitsRequest } from './models/SendSongSplitsRequest';
export type { ShareCompositionAgreementRequest } from './models/ShareCompositionAgreementRequest';
export type { ShowResponse } from './models/ShowResponse';
export type { SimpleQuoteResponse } from './models/SimpleQuoteResponse';
export type { SimpleRoyaltyDealDetailResponse } from './models/SimpleRoyaltyDealDetailResponse';
export { SimpleRoyaltyDealType } from './models/SimpleRoyaltyDealType';
export type { SongDetailResponse } from './models/SongDetailResponse';
export { SongStatus } from './models/SongStatus';
export type { SongSummary } from './models/SongSummary';
export type { SongSummaryResponse } from './models/SongSummaryResponse';
export type { SongwriterIdentityRequest } from './models/SongwriterIdentityRequest';
export type { SongwriterIdentityResponse } from './models/SongwriterIdentityResponse';
export type { StatisticsResponse } from './models/StatisticsResponse';
export { SXLODStatus } from './models/SXLODStatus';
export type { SyncLicenseDealResponse } from './models/SyncLicenseDealResponse';
export { TeamAccessType } from './models/TeamAccessType';
export type { TeamDetailResponse } from './models/TeamDetailResponse';
export type { TeamMemberRequest } from './models/TeamMemberRequest';
export type { TeamMemberResponse } from './models/TeamMemberResponse';
export type { TeamSummaryResponse } from './models/TeamSummaryResponse';
export { Territory } from './models/Territory';
export { ThresholdType } from './models/ThresholdType';
export type { TrackAssetsResponse } from './models/TrackAssetsResponse';
export type { TrackResponse } from './models/TrackResponse';
export { TrackVersion } from './models/TrackVersion';
export type { UpdateArtistRequest } from './models/UpdateArtistRequest';
export type { UpdateBusinessCardSettingsRequest } from './models/UpdateBusinessCardSettingsRequest';
export type { UpdateClientBankingInfoRequest } from './models/UpdateClientBankingInfoRequest';
export type { UpdateCompositionAgreementPublisherEntityRequest } from './models/UpdateCompositionAgreementPublisherEntityRequest';
export type { UpdateCompositionAgreementRequest } from './models/UpdateCompositionAgreementRequest';
export type { UpdateContractingInfoRequest } from './models/UpdateContractingInfoRequest';
export type { UpdateContributorRequest } from './models/UpdateContributorRequest';
export type { UpdateInvoiceClientRequest } from './models/UpdateInvoiceClientRequest';
export type { UpdateInvoiceRequest } from './models/UpdateInvoiceRequest';
export type { UpdateLivePerformanceDealRequest } from './models/UpdateLivePerformanceDealRequest';
export type { UpdateManagerRequest } from './models/UpdateManagerRequest';
export type { UpdateMasterAgreementRequest } from './models/UpdateMasterAgreementRequest';
export type { UpdateMasterArtistRequest } from './models/UpdateMasterArtistRequest';
export type { UpdateMasterDealRequest } from './models/UpdateMasterDealRequest';
export type { UpdateMasterRequest } from './models/UpdateMasterRequest';
export type { UpdateNeighboringRightsDealRequest } from './models/UpdateNeighboringRightsDealRequest';
export type { UpdatePubDealContactRequest } from './models/UpdatePubDealContactRequest';
export type { UpdatePubDealRequest } from './models/UpdatePubDealRequest';
export type { UpdatePublisherEntityRequest } from './models/UpdatePublisherEntityRequest';
export type { UpdateRecordDealRequest } from './models/UpdateRecordDealRequest';
export type { UpdateReleaseAssetRequest } from './models/UpdateReleaseAssetRequest';
export type { UpdateReleaseEventRequest } from './models/UpdateReleaseEventRequest';
export type { UpdateReleaseIntegrationStatusRequest } from './models/UpdateReleaseIntegrationStatusRequest';
export type { UpdateReleasePermissionsRequest } from './models/UpdateReleasePermissionsRequest';
export type { UpdateReleaseRequest } from './models/UpdateReleaseRequest';
export type { UpdateReleaseTerritoryRequest } from './models/UpdateReleaseTerritoryRequest';
export type { UpdateSimpleRoyaltyDealRequest } from './models/UpdateSimpleRoyaltyDealRequest';
export type { UpdateSongRequest } from './models/UpdateSongRequest';
export type { UpdateSongwriterIdentityRequest } from './models/UpdateSongwriterIdentityRequest';
export type { UpdateSyncLicenseDealRequest } from './models/UpdateSyncLicenseDealRequest';
export type { UpdateTeamRequest } from './models/UpdateTeamRequest';
export type { UpdateTrackRequest } from './models/UpdateTrackRequest';
export type { UpdateUserPreferencesRequest } from './models/UpdateUserPreferencesRequest';
export type { UserPreferencesResponse } from './models/UserPreferencesResponse';
export type { UserSummaryResponse } from './models/UserSummaryResponse';
export type { ValidationError } from './models/ValidationError';
export type { VerifiedClientBookResponse } from './models/VerifiedClientBookResponse';
export { ViewEditAccessType } from './models/ViewEditAccessType';
export type { W9UploadResponse } from './models/W9UploadResponse';

export { BusinessCardsService } from './services/BusinessCardsService';
export { DefaultService } from './services/DefaultService';
